import express from 'express';
import { chromium } from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs';

const app=express();app.use(express.json());app.use((q,r,n)=>{r.set('Access-Control-Allow-Origin','*');r.set('Access-Control-Allow-Headers','Content-Type');r.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(q.method==='OPTIONS')return r.sendStatus(204);n()});
let ctx,stop=false;const state={running:false,message:'Ready.',counts:{found:0,matched:0,applied:0,skipped:0,review:0},jobs:[]};
const profileDir=path.resolve('.naukri-profile'),historyFile=path.resolve('application-history.json');fs.mkdirSync(profileDir,{recursive:true});
const norm=s=>String(s||'').toLowerCase();const history=()=>{try{return JSON.parse(fs.readFileSync(historyFile,'utf8'))}catch{return {}}};const saveHistory=h=>fs.writeFileSync(historyFile,JSON.stringify(h,null,2));
const skillMatch=(text,skills=[])=>skills.length?Math.round(skills.filter(s=>norm(text).includes(norm(s))).length/skills.length*100):0;
const matchesAny=(text,list=[])=>!list.length||list.some(x=>norm(text).includes(norm(x)));
const slug=s=>encodeURIComponent(String(s||'').trim().replace(/\s+/g,'-').toLowerCase());
async function firstText(page,selectors){for(const s of selectors){const v=await page.locator(s).first().innerText().catch(()=>null);if(v?.trim())return v.trim()}return ''}
async function hasSecurityChallenge(page){const t=norm(await page.locator('body').innerText().catch(()=>''));return /captcha|verify you are human|security check|enter otp|one time password/.test(t)}
async function applyToJob(page,profile){if(await hasSecurityChallenge(page))return 'Needs manual login/security check';const body=await page.locator('body').innerText().catch(()=>'');if(/already applied/i.test(body))return 'Already Applied';
const apply=page.getByRole('button',{name:/apply/i}).or(page.locator('button:has-text("Apply")')).first();if(!await apply.isVisible().catch(()=>false))return 'Needs Review';await apply.click().catch(()=>{});await page.waitForTimeout(1200);if(await hasSecurityChallenge(page))return 'Needs manual login/security check';
// Only answer deterministic profile questions. Unknown questions are never invented.
const fields=[[/current.*ctc|current.*salary/i,profile.currentCtc],[/expected.*ctc|expected.*salary/i,profile.expectedCtc],[/notice.*period/i,profile.noticePeriod],[/experience/i,profile.experience]];
for(const [re,val] of fields){if(val===undefined||val===null||val==='')continue;const labels=page.locator('label');for(let i=0;i<await labels.count();i++){const l=labels.nth(i),txt=await l.innerText().catch(()=>'');if(!re.test(txt))continue;const id=await l.getAttribute('for');const input=id?page.locator('#'+CSS.escape(id)):l.locator('input,textarea').first();if(await input.count())await input.fill(String(val)).catch(()=>{})}}
const modalText=await page.locator('body').innerText().catch(()=>'');if(/screening question|answer the following|additional question/i.test(modalText)){const empty=page.locator('input:visible:not([type=hidden]),textarea:visible').filter({hasNot:page.locator('[disabled]')});for(let i=0;i<await empty.count();i++){if(!(await empty.nth(i).inputValue().catch(()=>'')))return 'Needs Review'}}
const submit=page.getByRole('button',{name:/submit|apply now|send application/i}).first();if(!await submit.isVisible().catch(()=>false))return 'Needs Review';if(process.env.LIVE_APPLY!=='true')return 'Matched - Dry Run';await submit.click();await page.waitForTimeout(1500);return 'Applied';}
async function run(p){state.running=true;stop=false;state.counts={found:0,matched:0,applied:0,skipped:0,review:0};state.jobs=[];const seen=history();try{ctx=await chromium.launchPersistentContext(profileDir,{headless:false,channel:'chrome'});const page=ctx.pages()[0]||await ctx.newPage();state.message='Opening Naukri. Login manually if requested.';await page.goto('https://www.naukri.com/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(5000);if(await hasSecurityChallenge(page)){state.message='Complete login/OTP/CAPTCHA manually in Chrome, then press Start again.';return}
for(const role of (p.roles||[])){if(stop)break;const url=`https://www.naukri.com/${slug(role)}-jobs`;state.message=`Searching ${role} jobs...`;await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(2500);const links=await page.locator('a[href*="job-listings"],a[href*="job-details"]').evaluateAll(as=>[...new Map(as.map(a=>[a.href,{url:a.href,role:(a.innerText||a.textContent||'').trim()}])).values()].slice(0,25)).catch(()=>[]);state.counts.found+=links.length;
for(const j of links){if(stop)break;if(seen[j.url]){state.counts.skipped++;continue}let jp;try{jp=await ctx.newPage();await jp.goto(j.url,{waitUntil:'domcontentloaded',timeout:30000});const text=(await jp.locator('body').innerText()).slice(0,60000),match=skillMatch(text,p.skills||[]),locationOK=matchesAny(text,p.locations||[]),roleOK=matchesAny(text,p.roles||[]);const company=await firstText(jp,['[class*="company"]','[class*="comp-name"]','a[class*="company"]'])||'Naukri employer';let status='Skipped';if(match>=Number(p.minMatch||75)&&locationOK&&roleOK){state.counts.matched++;status=await applyToJob(jp,p);if(status==='Applied')state.counts.applied++;else if(/Review|manual|Dry Run/.test(status))state.counts.review++;else state.counts.skipped++}else state.counts.skipped++;state.jobs.unshift({role:j.role||role,company,match,status,url:j.url});state.jobs=state.jobs.slice(0,50);seen[j.url]={status,date:new Date().toISOString(),match};saveHistory(seen)}catch(e){state.counts.review++;state.jobs.unshift({role:j.role||role,company:'Unknown',match:0,status:'Needs Review',url:j.url})}finally{if(jp)await jp.close().catch(()=>{})}}
}
state.message=stop?'Stopped.':process.env.LIVE_APPLY==='true'?'Run completed.':'Dry run completed. Set LIVE_APPLY=true only after reviewing matches.';}catch(e){state.message='Worker error: '+e.message}finally{state.running=false}}
app.get('/api/status',(_,r)=>r.json(state));app.post('/api/start',(q,r)=>{if(!state.running)run(q.body);r.json(state)});app.post('/api/stop',async(_,r)=>{stop=true;state.message='Stopping...';if(ctx)await ctx.close().catch(()=>{});ctx=null;state.running=false;r.json(state)});app.listen(8787,'127.0.0.1',()=>console.log('SK TECH worker http://127.0.0.1:8787 | LIVE_APPLY='+(process.env.LIVE_APPLY||'false')));