const $=id=>document.getElementById(id);const API=localStorage.getItem('sktechWorkerUrl')||window.location.origin;
const log=m=>{$('log').textContent+=`\n[${new Date().toLocaleTimeString()}] ${m}`;$('log').scrollTop=$('log').scrollHeight};
const profile=()=>({roles:$('roles').value.split(',').map(x=>x.trim()).filter(Boolean),experience:Number($('experience').value),skills:$('skills').value.split(',').map(x=>x.trim()).filter(Boolean),locations:$('locations').value.split(',').map(x=>x.trim()).filter(Boolean),minMatch:Number($('minMatch').value)});
function save(){localStorage.setItem('sktechNaukriProfile',JSON.stringify(profile()));log('Candidate settings saved locally.')}function load(){try{const p=JSON.parse(localStorage.getItem('sktechNaukriProfile'));if(!p)return;$('roles').value=p.roles.join(', ');$('experience').value=p.experience;$('skills').value=p.skills.join(', ');$('locations').value=p.locations.join(', ');$('minMatch').value=p.minMatch;$('matchLabel').textContent=p.minMatch+'%'}catch{}}
async function call(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error(await r.text()||r.statusText);return r.json()}
function render(s){$('found').textContent=s.counts?.found||0;$('matched').textContent=s.counts?.matched||0;$('applied').textContent=s.counts?.applied||0;$('skipped').textContent=s.counts?.skipped||0;$('review').textContent=s.counts?.review||0;$('workerStatus').textContent=s.running?'Worker running':'Worker connected';document.querySelector('.status').classList.add('online');$('startBtn').disabled=!!s.running;$('stopBtn').disabled=!s.running;$('runMessage').textContent=s.message||'Ready';const rows=(s.jobs||[]).map(j=>`<tr><td>${esc(j.role)}</td><td>${esc(j.company)}</td><td>${Number(j.match||0)}%</td><td><span class="badge">${esc(j.status)}</span></td></tr>`).join('');$('jobs').innerHTML=rows||'<tr><td colspan="4" class="empty">No applications yet.</td></tr>'}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function health(){try{render(await call('/api/status'))}catch{$('workerStatus').textContent='Worker offline';document.querySelector('.status').classList.remove('online')}}
$('minMatch').oninput=e=>$('matchLabel').textContent=e.target.value+'%';$('saveBtn').onclick=save;$('clearLog').onclick=()=>$('log').textContent='';
$('startBtn').onclick=async()=>{save();try{log('Starting Naukri worker...');render(await call('/api/start',{method:'POST',body:JSON.stringify(profile())}))}catch(e){log('Worker unavailable: '+e.message+' Start the local Node.js worker first.')}};
$('stopBtn').onclick=async()=>{try{render(await call('/api/stop',{method:'POST',body:'{}'}));log('Stop requested.')}catch(e){log(e.message)}};
load();health();setInterval(health,5000);